"""Validate published local references and JavaScript without calling external APIs."""
from html.parser import HTMLParser
from pathlib import Path
from urllib.parse import unquote, urlsplit
import shutil
import subprocess
import sys

root = Path(sys.argv[1] if len(sys.argv) > 1 else '.').resolve()
excluded = {'.git', '.github', 'node_modules', 'public-dist', '.wrangler'}
files = [p for p in root.rglob('*') if p.is_file() and not excluded.intersection(p.relative_to(root).parts)]
errors = []
scripts = set()


class Page(HTMLParser):
    def __init__(self, path):
        super().__init__()
        self.path = path
        self.script = None
    def handle_starttag(self, tag, attrs):
        attrs = dict(attrs)
        for key in ('src', 'href'):
            ref = attrs.get(key, '')
            url = urlsplit(ref)
            if url.scheme or url.netloc or not url.path:
                continue
            target = ((root if url.path.startswith('/') else self.path.parent) / unquote(url.path).lstrip('/')).resolve()
            if not target.is_relative_to(root):
                errors.append(f'{self.path.relative_to(root)}: path outside site root')
                continue
            candidates = [target, target / 'index.html', Path(str(target) + '.html')]
            if not any(p.is_file() and p.stat().st_size > 0 for p in candidates):
                errors.append(f'{self.path.relative_to(root)}: missing {ref}')
            if tag == 'script' and key == 'src':
                scripts.add(target)
        if tag == 'script' and not attrs.get('src') and attrs.get('type', '') in ('', 'module', 'text/javascript'):
            self.script = []
    def handle_data(self, data):
        if self.script is not None:
            self.script.append(data)
    def handle_endtag(self, tag):
        if tag == 'script' and self.script is not None:
            result = subprocess.run(['node', '--input-type=module', '--check'], input=''.join(self.script), text=True, capture_output=True)
            if result.returncode:
                errors.append(f'{self.path.relative_to(root)}: inline JavaScript syntax error')
            self.script = None


pages = [p for p in files if p.suffix == '.html']
if not pages:
    errors.append('No HTML pages found')
for page in pages:
    parser = Page(page)
    parser.feed(page.read_text(encoding='utf-8'))
for script in scripts:
    result = subprocess.run(['node', '--check', str(script)], capture_output=True)
    if result.returncode:
        errors.append(f'{script.relative_to(root)}: JavaScript syntax error')
if errors:
    raise SystemExit('\n'.join(errors))
print(f'Passed: {len(pages)} HTML pages, local references, inline scripts and {len(scripts)} linked scripts')

if '--build' in sys.argv:
    output = root / 'public-dist'
    if output.is_symlink():
        raise SystemExit('Refusing symlink output directory')
    if output.exists():
        if not (output / '.generated-static-build').is_file():
            raise SystemExit('Refusing to replace an unknown output directory')
        shutil.rmtree(output)
    output.mkdir()
    extensions = {'.html', '.css', '.js', '.mjs', '.png', '.jpg', '.jpeg', '.webp', '.avif', '.gif', '.svg', '.ico', '.woff', '.woff2', '.ttf', '.mp3', '.m4a', '.wav', '.mp4', '.webm', '.xml', '.webmanifest'}
    special = {'robots.txt', 'ads.txt', 'llms.txt', '_headers', '_redirects', '_routes.json'}
    for path in files:
        if path.suffix.lower() not in extensions and path.name not in special:
            continue
        target = output / path.relative_to(root)
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(path, target)
    (output / '.generated-static-build').write_text('Generated by check_site.py\n')
    print('Static publish directory: ' + str(output))
